name: Quartz CI/CD

on:
  push:
    branches:
      - v4  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Quartz
        run: npx quartz build

      - name: Sync to Server via rsync
        uses: Burnett01/rsync-deployments@8.0.4
        with:
          switches: -avzr --delete  # -a 归档模式, -v 详细, -z 压缩, -r 递归, --delete 删除目标目录中多余文件
          path: public/
          remote_path: /var/www/quartz/public/ # 注意：这里直接同步到 public 内部
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Reset Permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 使用 sudo 确保 Nginx 权限，因为同步过去的文件属主是 devuser
            chmod -R 775 /var/www/quartz/public